### ISSUE TITLE
api 数据错误

### ISSUE THREAD

**Issue by cctanfujun** [otcbtc/otcbtc-exchange-api-doc#12]
使用 /api/v2/order_book 获取的数据和网站显示不一致 

参数 adaeth asks_limit=1 bids_limit=1

如下是获取的数据
{'asks': [{'id': 43590336, 'side': 'sell', 'ord_type': 'limit', 'price': '0.00035999', 'avg_price': '0.0', 'state': 'wait', 'market': 'adaeth', 'created_at': '2018-06-05T11:17:05+08:00', 'volume': '5081.71673807', 'remaining_volume': '5081.71673807', 'executed_volume': '0.0', 'trades_count': 0}], 'bids': [{'id': 43216797, 'side': 'buy', 'ord_type': 'limit', 'price': '0.00036076', 'avg_price': '0.0', 'state': 'wait', 'market': 'adaeth', 'created_at': '2018-06-04T13:02:28+08:00', 'volume': '1097.08317516', 'remaining_volume': '1097.08317516', 'executed_volume': '0.0', 'trades_count': 0}]}

如下是网站数据截图
![image](https://user-images.githubusercontent.com/7422247/40953788-dcc7a708-68b3-11e8-8459-8116b30f6c7a.png)

**Comment by cctanfujun** [comment]
看起来好像是ask和bid都返回来卖单

**Comment by cctanfujun** [comment]
好像fix了  关闭这个bug

**Comment by cctanfujun** [comment]
问题依旧

**Comment by 0tcbtc** [comment]
The endpoint /api/v2/order_book will be deprecated soon, please check our latest doc and use /api/v2/depth instead.
