### ISSUE TITLE
能否增加websocket的api呢？

### ISSUE THREAD

**Issue by catalsdevelop** [otcbtc/otcbtc-exchange-api-doc#7]
好多人的server都在海外，延迟还是比较大的，能不能把行情这种实时性强的api，增加ws的接口呢

**Comment by haichong01** [comment]
支持，现在获取行情都是客户端发起轮询，对server端压力也大，而且api文档也没有明确告知 调用次数/间隔限制

**Comment by 0tcbtc** [comment]
Added

[doc](/WEB_SOCKET_API.md)
